# Generated by Django 3.2.5 on 2021-07-05 06:43

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Helpful text', max_length=256, verbose_name='name')),
                ('slug', models.SlugField(help_text='Helpful text', verbose_name='slug')),
                ('url', models.URLField(help_text='Helpful text', verbose_name='url')),
                ('email', models.EmailField(help_text='Helpful text', max_length=254, verbose_name='email')),
                ('birthday', models.DateField(help_text='Helpful text', verbose_name='birthday')),
                ('friends', models.ManyToManyField(blank=True, help_text='Helpful text', related_name='_demo_app_person_friends_+', to='demo_app.Person')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_and_time', models.DateTimeField(help_text='Helpful text', verbose_name='date and time')),
                ('picture', models.ImageField(help_text='Helpful text', upload_to='pictures', verbose_name='picture')),
                ('is_color', models.BooleanField(default=True, help_text='Helpful text', verbose_name='color')),
                ('person', models.ForeignKey(help_text='Helpful text', on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='demo_app.person')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'picture',
                'verbose_name_plural': 'pictures',
                'ordering': ('-date_and_time',),
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ForeignKey(help_text='Helpful text', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='demo_app.person')),
                ('picture', models.ForeignKey(help_text='Helpful text', on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='demo_app.picture')),
            ],
            options={
                'verbose_name': 'favorite',
                'verbose_name_plural': 'favorites',
            },
        ),
    ]
